// <auto-generated />
namespace Web_Kladilnica.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class stuff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stuff));
        
        string IMigrationMetadata.Id
        {
            get { return "201909231244010_stuff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
